apiVersion: apps/v1
kind: Deployment
metadata:
  name: secureshop-api
  labels:
    app: secureshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secureshop
  template:
    metadata:
      labels:
        app: secureshop
    spec:
      containers:
      - name: secureshop
        image: ghcr.io/dbraca11/secureshop:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
